camel:
  springboot:
    #    Sollte sich der Camel Main Thread nach dem Start wieder beenden, folgende Property aktivieren (http://camel.apache.org/spring-boot.html).
    main-run-controller: true
    tracing: false
  component:
    aws2-s3:
      region: ...
      override-endpoint: ...
    http:
      proxy-auth-host: ...
      proxy-auth-port: ...
      proxy-auth-scheme: ...
  metrics:
    enable-message-history: false

spring:
  application:
    name: '@project.artifactId@'
  security:
    oauth2:
      client:
        registration:
          custom:
            provider: ...
            client-id: ...
            client-secret: ...
            authorization-grant-type: ...
        provider:
          custom:
            token-uri: ...

# https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  info:
    env:
      enabled: true
    camel:
      enabled: false
#  metrics:
#    distribution:
#      percentiles-histogram:
#        http:
#          server-request: true
#          client-request: true

info:
  application:
    name: '@project.artifactId@'
    version: '@project.version@'

logging:
  level:
    org:
      springframework: INFO

oauth2:
  registration:
    id: ...

de.muenchen.mobidam:
  integration:
    baseUrl: ...
    interfaces:
      interface-1:
        mobidam-sst-id:
        name:
        mobilithek-url:
        cron-expression:
        s3-object-path:
        s3-date-format:
        s3-bucket:
        allowed-resource-types:
        malicious-code-detection-enabled:
  data:
    review-specification:
      malicious-data-regex:
        key:
    defined-resource-types:
      resource-types:
        xml:
          allowed-mime-types:
        csv:
          allowed-mime-types:
  eai:
    cacerts-file: ...
    cacerts-password: ...
  common:
    s3:
      bucket-credential-configs:
        s3-bucket-1:
          access-key-env-var: ...
          secret-key-env-var: ...
  metrics:
    beginn-counter-metric: mobidam.exchanges.ereignis.beginn.counter
    ende-counter-metric: mobidam.exchanges.ereignis.ende.counter
    fehler-counter-metric: mobidam.exchanges.ereignis.fehler.counter
    erfolg-counter-metric: mobidam.exchanges.ereignis.erfolg.counter
    warnungen-counter-metric: mobidam.exchanges.ereignis.warnungen.counter
    inflight-exchanges-metric: mobidam.exchanges.inflight
    processing-time-metric: mobidam.exchanges.processingtime
    max-file-size-metric: mobidam.exchanges.filesize.max

