camel:
  springboot:
    #    Sollte sich der Camel Main Thread nach dem Start wieder beenden, folgende Property aktivieren (http://camel.apache.org/spring-boot.html).
    main-run-controller: true
    tracing: false
  component:
    aws2-s3:
      region: ...
      override-endpoint: ...
    http:
      proxy-auth-host: ...
      proxy-auth-port: ...
      proxy-auth-scheme: ...

spring:
  application:
    name: '@project.artifactId@'
  security:
    oauth2:
      client:
        registration:
          custom:
            provider: ...
            client-id: ...
            client-secret: ...
            authorization-grant-type: ...
        provider:
          custom:
            token-uri: ...

# https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  info:
    env:
      enabled: true
    camel:
      enabled: false

info:
  application:
    name: '@project.artifactId@'
    version: '@project.version@'

logging:
  level:
    org:
      springframework: INFO

oauth2:
  registration:
    id: ...

de.muenchen.mobidam.integration:
  baseUrl: ...
  interfaces:
    interface-1:
      mobidam-sst-id:
      mobilithek-subscription-id: ...
      mobilithek-url:
      cron-expression:
      s3-object-path: ...
      s3-date-format: ...
      s3-bucket: s3-bucket-1

mobidam:
  s3:
    bucket-credential-config:
      s3-bucket-1:
        access-key-env-var: ...
        secret-key-env-var: ...